name: NodePinT CI/CD

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    # - name: Install dependencies
    #   run: |
    #     conda env update --file envs/env_daffyduck.yaml --name base
    # - name: Install datasets from GitHub
    #  run: |
    #    python -m pip install "datasets @ git+https://github.com/huggingface/datasets#datasets[jax]"
    - name: Install PyTorch CPU
      run: |
        python -m pip install torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cpu
    - name: Install NodePinT & Pytest
      run: |
        python setup.py develop && conda install pytest
    - name: Run Lorentz test
      run: |
        pytest --disable-warnings -q nodepint/tests/lorentz.py -k 'not test_neural_net and not test_step'
